import 'dart:ui';

class Translator {
  static Locale locale = const Locale('ar');

  static bool get isArabic => locale.languageCode == 'ar';

  static void toggleLocale() {
    locale = isArabic ? const Locale('en') : const Locale('ar');
  }

  static String translate(String key, [Map<String, String>? args]) {
    final translations = <String, Map<String, String>>{
      'en': {
        'login': 'Login',
        'login_subtitle': 'Sign in to access the Rayhan dashboard.',
        'username': 'Username',
        'password': 'Password',
        'required': 'This field is required.',
        'home_statistics': 'Home statistics',
        'dashboard_subtitle':
            'Track stock, filter sales by date, and generate a PDF report for the selected period.',
        'low_stock_alerts': 'Low Stock Alerts',
        'products': 'Products',
        'customers': 'Customers',
        'all_products_and_search': 'All products and search',
        'products_subtitle':
            'Read all products, search them, and open a selected product page with sell actions.',
        'generate_pdf': 'Generate PDF report',
        'export_all_data': 'Export all data',
        'import_latest_data': 'Import latest data',
        'total_bought': 'Total bought',
        'sold_in_range': 'Sold in range',
        'total_expenses': 'Total expenses',
        'sales_count': 'Sales count',
        'inventory_value': 'Inventory value',
        'best_product': 'Best selling product in selected period',
        'no_sales_in_range': 'No sales found in this date range.',
        'app_name': 'Rayhan',
        'pdf_report_saved': 'PDF report saved to {path}',
        'pdf_report_error': 'Could not export report: {error}',
        'pdf_report_no_data': 'No data available to generate a PDF report.',
        'pdf_report_saved_title': 'Report Saved',
        'pdf_report_saved_message':
            'PDF report has been saved to:\n\n{path}\n\nYou can access it using a file manager app that can browse internal storage.',
        'open_file': 'Open File',
        'ok': 'OK',
        'all_data_exported': 'All data exported to {path}',
        'import_data_success': 'Imported data from {path}',
        'import_data_failed': 'Import failed: {error}',
        'all_products_label': 'All products and search',

        'search_hint': 'Search products',
        'add_expense': 'Add expense',
        'finance': 'Finances',
        'date': 'Date',
        'amount': 'Amount',
        'reason': 'Reason',
        'save': 'Save',
        'cancel': 'Cancel',
        'no_expenses': 'No expenses recorded yet.',
        'language': 'Language',
        'logout': 'Logout',
        'home': 'Home',
        'add': 'Add',
        'sell': 'Sell',
        'toggle_language_tooltip': 'Toggle language',
        'low_stock_notifications_tooltip': 'Low stock notifications',
        'no_low_stock_items': 'No low stock items',
        'check_product_stock': 'Check product stock for "{product}"',
        'product_customer_summary':
            '{products} products • {customers} customers',
        'from': 'From',
        'to': 'To',
        'generating': 'Generating...',
        'exporting': 'Exporting...',
        'importing': 'Importing...',
        'products_overview': 'Stock quantity',
        'all_products_page_title': 'All products and search',
        'all_products_page_subtitle':
            'Read all products, search them, and open a selected product page with sell actions.',
        'search_products': 'Search products',
        'no_products_yet': 'No products yet',
        'no_products_yet_description':
            'Open the Add page and create the first product for Rayhan.',
        'no_matching_products': 'No matching products',
        'no_matching_products_description':
            'Try another keyword or clear the search field to see all products.',
        'all_products_healthy': 'All products have healthy stock levels.',
        'product_stock_levels': 'Product Stock Levels',
        'status': 'Status',
        'low': 'Low',
        'medium': 'Medium',
        'healthy': 'Healthy',
        'best_selling_product': 'Best selling product in selected period',
        'product_details_description':
            'Product details with total buy amount, sell price, and quantity in ml.',
        'name_label': 'Name',
        'bought_for_total_amount': 'Bought for total amount',
        'sell_price_per_mm': 'Sell price per ml',
        'quantity_in_mm': 'Quantity in ml',
        'remaining_stock_cost': 'Remaining stock cost',
        'actions': 'Actions',
        'sell_this_product': 'Sell this product',
        'delete_product': 'Delete product',
        'product_delete_confirm':
            'Are you sure you want to delete this product?',
        'product_deleted': 'Product deleted',
        'back': 'Back',
        'special_customers_discount':
            'Special customers discounts are available in the sell page.',
        'product_not_found': 'This product no longer exists.',
        'add_a_product': 'Add a product',
        'add_product_subtitle': '',
        'product_information': 'Product information',
        'save_product': 'Save product',
        'product_created': 'Product "{name}" created.',
        'edit_product': 'Edit product',
        'edit_product_subtitle': 'Update the product details.',
        'update_product': 'Update product',
        'product_updated': 'Product "{name}" updated.',
        'sell_a_product': 'Sell a product',
        'sell_product_subtitle':
            'Save full sale data, review every sale, and prepare report-ready records.',
        'product': 'Product',
        'special_customer': 'Special customer',
        'no_special_customer': 'No special customer',
        'discount_percent': 'Discount percent',
        'final_price': 'Final price',
        'use_suggested_total': 'Use suggested total',
        'confirm_sale': 'Confirm sale',
        'sales_history': 'Sales history',
        'no_sales_saved': 'No sales saved yet.',
        'regular_customer': 'Regular customer',
        'current_stock': 'Current stock',
        'saved_sales': 'Saved sales',
        'unit_price_per_mm': 'Unit price per ml',
        'customer': 'Customer',
        'subtotal': 'Subtotal',
        'discount': 'Discount',
        'suggested_total': 'Suggested total',
        'final_total': 'Final total',
        'quantity': 'Quantity',
        'unit_price': 'Unit price',
        'sale_saved': 'Sale saved for {product}{customer}: {total}',
        'sell_empty_state': 'Add at least one product before recording a sale.',
        'all_time_sold': 'All-time sold',
        'add_customer': 'Add customer',
        'special_customers': 'Special customers',
        'customers_subtitle': '',
        'delete_customer': 'Delete customer',
        'delete_customer_confirmation': 'Delete {name} from special customers?',
        'delete': 'Delete',
        'no_special_customers_yet': 'No special customers yet.',
        'edit_customer': 'Edit customer',
        'add_customer_dialog_title': 'Add customer',
        'customer_id': 'Customer ID',
        'phone_label': 'Phone',
        'discount_percent_label': 'Discount percent',
        'notes_label': 'Notes',
        'field_required': 'This field is required.',
        'discount_range_error': 'Enter a discount from 0 to 100.',
        'total_expenses_label': 'Total Expenses:',
        'no_expenses_recorded_yet': 'No expenses recorded yet.',
        'finances': 'Finances',
        'app_name': 'Rayhan',
        'pdf_report_saved': 'تم حفظ تقرير PDF في {path}',
        'pdf_report_error': 'تعذر تصدير التقرير: {error}',
        'pdf_report_no_data': 'لا توجد بيانات لإنشاء تقرير PDF.',
        'pdf_report_saved_title': 'تم حفظ التقرير',
        'pdf_report_saved_message':
            'تم حفظ تقرير PDF في:\n\n{path}\n\nيمكنك الوصول إليه باستخدام تطبيق مدير ملفات يمكنه تصفح التخزين الداخلي.',
        'open_file': 'فتح الملف',
        'ok': 'موافق',
        'all_data_exported': 'تم تصدير جميع البيانات إلى {path}',
        'import_data_success': 'تم استيراد البيانات من {path}',
        'import_data_failed': 'فشل الاستيراد: {error}',
        'track_business_expenses': 'Track your business expenses.',
        'delete_expense': 'Delete expense',
        'delete_expense_confirmation': 'Delete expense "{reason}"?',
        'add_expense_dialog_title': 'Add Expense',
        'edit_expense_dialog_title': 'Edit Expense',
        'please_select_date': 'Please select a date',
        'please_enter_amount': 'Please enter an amount',
        'please_enter_valid_amount': 'Please enter a valid amount',
        'please_enter_reason': 'Please enter a reason',
        'print_date': 'Date',
      },
      'ar': {
        'login': 'تسجيل الدخول',
        'login_subtitle': 'سجل الدخول للوصول إلى لوحة تحكم ريحان.',
        'username': 'اسم المستخدم',
        'password': 'كلمة المرور',
        'required': 'هذا الحقل مطلوب.',
        'home_statistics': 'إحصائيات الصفحة الرئيسية',
        'dashboard_subtitle':
            'تتبع المخزون، وفرز المبيعات حسب التاريخ، وإنشاء تقرير PDF للفترة المحددة.',
        'low_stock_alerts': 'تنبيهات النفاد',
        'products': 'المنتجات',
        'customers': 'العملاء',
        'all_products_and_search': 'جميع المنتجات والبحث',
        'products_subtitle':
            'عرض جميع المنتجات، ابحث عنها، وافتح صفحة المنتج المحددة لإجراءات البيع.',
        'generate_pdf': 'إنشاء تقرير PDF',
        'export_all_data': 'تصدير جميع البيانات',
        'import_latest_data': 'استيراد أحدث البيانات',
        'total_bought': 'إجمالي المشتريات',
        'sold_in_range': 'المباعة في الفترة',
        'total_expenses': 'إجمالي المصاريف',
        'sales_count': 'عدد المبيعات',
        'inventory_value': 'قيمة المخزون',
        'best_product': 'أفضل منتج مبيعًا في الفترة المحددة',
        'no_sales_in_range': 'لا توجد مبيعات في هذه الفترة.',
        'all_products_label': 'جميع المنتجات والبحث',
        'search_hint': 'ابحث عن المنتجات',
        'add_expense': 'إضافة مصاريف',
        'finance': 'المالية',
        'date': 'التاريخ',
        'amount': 'المبلغ',
        'reason': 'السبب',
        'save': 'حفظ',
        'cancel': 'إلغاء',
        'no_expenses': 'لا توجد مصاريف مسجلة بعد.',
        'language': 'اللغة',
        'logout': 'تسجيل الخروج',
        'home': 'الرئيسية',
        'add': 'إضافة',
        'sell': 'بيع',
        'toggle_language_tooltip': 'تبديل اللغة',
        'low_stock_notifications_tooltip': 'تنبيهات نفاد المخزون',
        'no_low_stock_items': 'لا توجد عناصر نفاذ مخزون',
        'check_product_stock': 'تحقق من مخزون المنتج "{product}"',
        'product_customer_summary': '{products} منتج • {customers} عميل',
        'from': 'من',
        'to': 'إلى',
        'generating': 'جارٍ الإنشاء...',
        'exporting': 'جارٍ التصدير...',
        'importing': 'جارٍ الاستيراد...',
        'products_overview': 'كمية المخزون',
        'all_products_page_title': 'جميع المنتجات والبحث',
        'all_products_page_subtitle':
            'عرض جميع المنتجات، ابحث عنها، وافتح صفحة المنتج المحددة لإجراءات البيع.',
        'search_products': 'ابحث عن المنتجات',
        'no_products_yet': 'لا توجد منتجات بعد',
        'no_products_yet_description':
            'افتح صفحة الإضافة وأنشئ المنتج الأول لريحان.',
        'no_matching_products': 'لا توجد منتجات مطابقة',
        'no_matching_products_description':
            'جرب كلمة مفتاحية أخرى أو امسح خانة البحث لرؤية جميع المنتجات.',
        'all_products_healthy': 'جميع المنتجات لديها مستويات مخزون صحية.',
        'product_stock_levels': 'مستويات مخزون المنتج',
        'status': 'الحالة',
        'low': 'منخفض',
        'medium': 'متوسط',
        'healthy': 'صحي',
        'best_selling_product': 'أفضل منتج مبيعًا في الفترة المحددة',
        'product_details_description':
            'تفاصيل المنتج مع إجمالي سعر الشراء، وسعر البيع، والكمية بالمليلتر.',
        'name_label': 'الاسم',
        'bought_for_total_amount': 'تم شراؤه بمبلغ إجمالي',
        'sell_price_per_mm': 'سعر البيع لكل مل',
        'quantity_in_mm': 'الكمية بالمليلتر',
        'remaining_stock_cost': 'تكلفة المخزون المتبقي',
        'actions': 'الإجراءات',
        'sell_this_product': 'بيع هذا المنتج',
        'delete_product': 'حذف المنتج',
        'product_delete_confirm': 'هل أنت متأكد أنك تريد حذف هذا المنتج؟',
        'product_deleted': 'تم حذف المنتج',
        'back': 'عودة',
        'special_customers_discount':
            'خصومات العملاء المميزين متاحة في صفحة البيع.',
        'product_not_found': 'هذا المنتج لم يعد موجودًا.',
        'add_a_product': 'إضافة منتج',
        'add_product_subtitle': '',
        'product_information': 'معلومات المنتج',
        'save_product': 'حفظ المنتج',
        'product_created': 'تم إنشاء المنتج "{name}".',
        'edit_product': 'تعديل المنتج',
        'edit_product_subtitle': 'تحديث تفاصيل المنتج.',
        'update_product': 'تحديث المنتج',
        'product_updated': 'تم تحديث المنتج "{name}".',
        'sell_a_product': 'بيع منتج',
        'sell_product_subtitle':
            'حفظ بيانات البيع الكاملة، وعرض كل عملية بيع، وتجهيز سجلات جاهزة للتقارير.',
        'product': 'المنتج',
        'special_customer': 'العميل المميز',
        'no_special_customer': 'لا يوجد عميل مميز',
        'discount_percent': 'نسبة الخصم',
        'final_price': 'السعر النهائي',
        'use_suggested_total': 'استخدام الإجمالي المقترح',
        'confirm_sale': 'تأكيد البيع',
        'sales_history': 'سجل المبيعات',
        'no_sales_saved': 'لا توجد مبيعات محفوظة بعد.',
        'regular_customer': 'عميل عادي',
        'current_stock': 'المخزون الحالي',
        'saved_sales': 'المبيعات المحفوظة',
        'unit_price_per_mm': 'سعر الوحدة لكل مل',
        'customer': 'العميل',
        'subtotal': 'الإجمالي الفرعي',
        'discount': 'الخصم',
        'suggested_total': 'الإجمالي المقترح',
        'final_total': 'الإجمالي النهائي',
        'quantity': 'الكمية',
        'unit_price': 'سعر الوحدة',
        'sale_saved': 'تم حفظ البيع لـ {product}{customer}: {total}',
        'sell_empty_state': 'أضف منتجًا واحدًا على الأقل قبل تسجيل عملية بيع.',
        'all_time_sold': 'الإجمالي المبيع حتى الآن',
        'add_customer': 'إضافة عميل',
        'special_customers': 'العملاء المميزون',
        'customers_subtitle': '',
        'delete_customer': 'حذف العميل',
        'delete_customer_confirmation': 'حذف {name} من العملاء المميزين؟',
        'no_special_customers_yet': 'لا يوجد عملاء مميزون بعد.',
        'edit_customer': 'تعديل العميل',
        'add_customer_dialog_title': 'إضافة عميل',
        'customer_id': 'معرف العميل',
        'phone_label': 'الهاتف',
        'discount_percent_label': 'نسبة الخصم',
        'notes_label': 'ملاحظات',
        'field_required': 'هذا الحقل مطلوب.',
        'discount_range_error': 'الرجاء إدخال خصم بين 0 و 100.',
        'total_expenses_label': 'إجمالي المصاريف:',
        'no_expenses_recorded_yet': 'لا توجد مصاريف مسجلة بعد.',
        'finances': 'المالية',
        'track_business_expenses': 'تتبع مصاريف عملك.',
        'delete_expense': 'حذف المصروف',
        'delete_expense_confirmation': 'حذف المصروف "{reason}"؟',
        'add_expense_dialog_title': 'إضافة مصروف',
        'edit_expense_dialog_title': 'تعديل المصروف',
        'please_select_date': 'الرجاء اختيار تاريخ',
        'please_enter_amount': 'الرجاء إدخال المبلغ',
        'please_enter_valid_amount': 'الرجاء إدخال مبلغ صالح',
        'please_enter_reason': 'الرجاء إدخال سبب',
        'print_date': 'التاريخ',
      },
    };

    var translated = translations[locale.languageCode]?[key] ?? key;
    if (args != null && args.isNotEmpty) {
      for (final entry in args.entries) {
        translated = translated.replaceAll('{${entry.key}}', entry.value);
      }
    }

    return translated;
  }
}
